server:
  port: 8888

spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
      location: C:/upload
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url:jdbc:mysql://localhost:3307/svs?allowPublicKeyRetrieval=true}
    username: ${db.username:root}
    password: ${db.password:root}
    hikari:
      connectionTimeout: 10000
      idleTimeout: 600000
      maximum-pool-size: 300
      minimum-idle: 5
      maxLifetime: 10000
      leak-detection-threshold: 2000
  jpa:
    hibernate:
      ddl-auto: none # `none` or `validate`.  Flyway -> DDL, JPA -> DDL (X)
    properties:
      hibernate:
        format-sql: false
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    schemas: svs

logging:
  level:
    root: info
    com.svs: debug
    
svs:
  predict:
    server: http://127.0.0.1:8000/items