CREATE TABLE IF NOT EXISTS REPLY (
    ID              BIGINT              AUTO_INCREMENT	PRIMARY KEY,
    REPLYTEXT       VARCHAR(1000)       NOT NULL,
    BOARDNUM        BIGINT              NOT NULL,
    USER_ID         VARCHAR(30)         NOT NULL,
    INPUT_DATE      DATETIME            DEFAULT now(),
    FOREIGN KEY(USER_ID) REFERENCES MEMBER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY(BOARDNUM) REFERENCES BOARD(ID) ON DELETE CASCADE 
);
