CREATE TABLE IF NOT EXISTS BOARD (
    ID              BIGINT              AUTO_INCREMENT	PRIMARY KEY,
    TITLE           VARCHAR(300)        NOT NULL,
    CONTENT         VARCHAR(4000)       NOT NULL,
    VIEW_COUNT      INT                 DEFAULT 0    NOT NULL,
    INPUT_DATE      DATETIME            DEFAULT now(),
    USER_ID         VARCHAR(30)         NOT NULL,
    BOARDTYPE       VARCHAR(100)        NOT NULL,
    ORIGINALFILE    VARCHAR(1000),
    SAVEDFILE       VARCHAR(1000),
    FOREIGN KEY(USER_ID) REFERENCES MEMBER(USER_ID) ON DELETE CASCADE           
);