CREATE TABLE IF NOT EXISTS BUSINESS (
    ID                  BIGINT              AUTO_INCREMENT	PRIMARY KEY,
    BUSINESS_NAME       VARCHAR(300)        NOT NULL,
    BUSINESS_ADDRESS    VARCHAR(500)        NOT NULL,
    USER_ID             VARCHAR(30)         NOT NULL,
    PHONE               VARCHAR(30),
    FOREIGN KEY(USER_ID) REFERENCES MEMBER(USER_ID) ON DELETE CASCADE
);