CREATE TABLE IF NOT EXISTS ROOMS (
    ID                  BIGINT              AUTO_INCREMENT	PRIMARY KEY,
    BUSINESS_NUM   BIGINT   NOT NULL,
    ROOM_NAME   VARCHAR(255)   NOT NULL,
    FOREIGN KEY(BUSINESS_NUM) REFERENCES BUSINESS(ID) ON DELETE CASCADE
);

